apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fqrkksrc5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fqrkksrc5-java-springboot-gitops